// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uirslybumcllfbwfvcru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcnNseWJ1bWNsbGZid2Z2Y3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTE3NjAsImV4cCI6MjA2NDU4Nzc2MH0.1hONC_m8VkG2Cm7S26A7eKfzlMczxL5PXIk7DuJIDT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);